### ISSUE TITLE
Expose query object from getUsersInRole

### ISSUE THREAD

**Issue by czeslaaw** [alanning/meteor-roles#100]
Hi

I use your package a lot and it is great. I wonder if you could add possibility to get query object from getUsersInRole function, right before it calls Meteor.users.find. 

Something like 
```
_getUsersInRoleQuery(role, group) {
  // same logic as getUsersInRole but returns query object instead of calling Meteor.users.find
}
```
then getUsersInRole would be just
```
getUsersInRole(role, group) {
  return Meteor.users.find(_getUsersInRoleQuery(role, group));
}
```

It would be useful is scenarios:
* extending query with additional fields
* use as query in update, remove or findOne
* use with different find options
* i am not sure but i guess it can be used internally in userIsInRole function

I can do PR but i wonder if you think this is a good idea.

Thanks a lot :)

**Comment by mitar** [comment]
Done in v2.0 branch.
