### ISSUE TITLE
Can't add users to roles

### ISSUE THREAD

**Issue by stlouisweb** [alanning/meteor-roles#101]
Roles.addUsersToRoles isn't working:

Error: When the modifier option is true, validation object must have at least one operator

**Comment by alanning** [comment]
A few questions to help narrow down the cause:

Is this error coming from MongoDB or another package? (Stack trace)

Which packages are you using in the app?

Can you provide a small repro?

**Comment by stlouisweb** [comment]
The error appears to be coming from simpleschema.

Here is the package list:
meteor-platform
autopublish
msavin:mongol
insecure
less
momentjs:moment
mrt:bootswatch-yeti
natestrauser:font-awesome
accounts-password
useraccounts:bootstrap
aldeed:collection2
aldeed:autoform
jplack:bootstrap-timepicker
iron:router
reactive-var
dburles:collection-helpers
yogiben:admin

Thanks

**Comment by alanning** [comment]
Sometimes the packages that modify the collection prototypes don't handle
things properly. Try adding "alanning:roles" as the first package after
meteor-platform in the .meteor/packages file and see if that helps.

Otherwise, pls provide a small repro app and I'll help debug further.
