### ISSUE TITLE
Make null publication more performant

### ISSUE THREAD

**Issue by dalgard** [alanning/meteor-roles#103]
With the `FastRender` package, all null publications are processed on every single request, including simple resource requests. This means that the publish function will be called many times before `this.userId` becomes available, so its performance can be improved a lot:

```javascript
// roles_server.js
Meteor.publish(null, function () {
  if (this.userId) {
    return Meteor.users.find(this.userId, {
        fields: { roles: 1 }
      });
  }

  this.ready();
});
```

**Comment by alanning** [comment]
Just released v1.2.14, which changes the null pub to a named pub.
