### ISSUE TITLE
how do I specify fields on the `Roles.getUsersInRole`?

### ISSUE THREAD

**Issue by AlexFrazer** [alanning/meteor-roles#109]
It returns a cursor. Now how do I specify fields? Perhaps a final parameter should be added to specify a projection

**Comment by alanning** [comment]
Right now there's no way to specify fields.  It's a good suggestion to include another parameter and there is already a PR that makes the required changes: https://github.com/alanning/meteor-roles/pull/77.

For your case, I'd suggest forking the repo, adding the PR, then copying the roles directory from the meteor-roles repo into your `.meteor/packages`.  Make sure that the name of the directory matches what the package system expects (not sure if you need to name the directory `alanning:roles`, `alanning_roles`, or just `roles`).

Please keep in mind that the `Roles.getUsersInRole` function runs a full collection scan on the users collection so it should not be used in critical performance code paths.

**Comment by alanning** [comment]
Merged #77 which resolves this issue.  Roles v1.2.14 will be released soon and will contain this fix.  Upcoming Roles v2.0 release will change the underlying database structure used which will allow indexing and avoid the full collection scan.
