### ISSUE TITLE
Edit existing roles

### ISSUE THREAD

**Issue by tgienger** [alanning/meteor-roles#112]
Should be a way to edit a role and have the change propagated throughout the db. ie: change the name and all users with that role will have their roles updated with the new name. If there is I missed it.

**Comment by alanning** [comment]
Good idea, this should be part of the package.  In the meantime, I've published the script that we use to rename roles:  https://gist.github.com/alanning/7aeac128f065e4571095

**Comment by alexpyslar** [comment]
Hello, so is there a solution for editing roles?
e.g. I want to add a description field for every role?

**Comment by alanning** [comment]
Still need to use the provided script to rename roles.  Adding descriptions for roles is out of the scope of this package at the moment.  To implement that, we'd have to also implement i18n which we've been able to successfully avoid so far.  :-)

**Comment by mitar** [comment]
Adding description field can be easily added by adding your own fields to the `Meteor.roles` collection. The package itself is not really using many fields, so you can feel safe adding your own extra information to it.

Although, for description I would rather suggest that you use a package like [tap-i18n](https://github.com/TAPevents/tap-i18n). Then you use role name as a key into the translatable description. So no need to store description in the database. You just convert it at runtime.

But if you want to store some user-specified description, just use `Meteor.roles`.

**Comment by mitar** [comment]
Renaming of roles available in the v2.0 branch.
