### ISSUE TITLE
Very strange. Added users to nonexisting roles..

### ISSUE THREAD

**Issue by elfatherbrown** [alanning/meteor-roles#113]
Hi, I did this from the meteor mongo shell:
>Roles.addUsersToRoles('SizjeiwS6suoTExbs',['admin','GOD'])
//admin exists, but GOD doesnt (no pun intended)

> Roles.getAllRoles().fetch()
[ { _id: 'ushGZ7ijEjgY5hhe8',
    userId: 'SizjeiwS6suoTExbs',
    roles: [ 'GOD', 'admin' ] },
  { _id: 'YpTK7SaESSJ3SuWPQ', name: 'admin' } ]
> Roles.setUserRoles('SizjeiwS6suoTExbs',[])
> Roles.getAllRoles().fetch()
[ { _id: 'ushGZ7ijEjgY5hhe8',
    userId: 'SizjeiwS6suoTExbs',
    roles: [ 'GOD', 'admin' ] },
  { _id: 'YpTK7SaESSJ3SuWPQ', name: 'admin' } ]

Strangely, I think, Roles.userHasRoles returns always an incorrect value after this:
> Roles.userIsInRole('SizjeiwS6suoTExbs','GOD')
false
> Roles.userIsInRole('SizjeiwS6suoTExbs','admin')
false
> Roles.userIsInRole('SizjeiwS6suoTExbs',['admin','GOD'])
false
> Roles.getRolesForUser('SizjeiwS6suoTExbs')
[]

No idea how to fix it. Setting all roles has no efect:
> Roles.getRolesForUser('SizjeiwS6suoTExbs')
[]
> Roles.setUserRoles('SizjeiwS6suoTExbs',[]);
> Roles.getRolesForUser('SizjeiwS6suoTExbs')
[]
> Roles.getAllRoles().fetch()
[ { _id: 'ushGZ7ijEjgY5hhe8',
    userId: 'SizjeiwS6suoTExbs',
    roles: [ 'GOD', 'admin' ] },
  { _id: 'YpTK7SaESSJ3SuWPQ', name: 'admin' } ]

Neither does Roles.deleteRole... :/

**Comment by alanning** [comment]
I'm surprised you could execute `Roles` functions from the meteor mongo shell.  Didn't think that was possible but pretty neat that it is.

Not quite sure what's happening here.  Please run this from the mongo shell and post the results:

`db.users.findOne({_id: 'SizjeiwS6suoTExbs'}, {roles: 1})`

**Comment by elfatherbrown** [comment]
Keep in mind i meant the meteor shell that comes up with "meteor shell",
not "meteor mongo" (the mongo shell)

It doesnt work from the mongo shell in the way you asked:

:meteor_test alex$ meteor shell
db.users.findOne({_id: 'SizjeiwS6suoTExbs'}, {roles: 1})
ReferenceError: db is not defined
    at repl:1:2
    at
/Users/alex/Devel/meteor_test/.meteor/local/build/programs/server/shell-server.js:243:23

This works though:

> Meteor.users.findOne({_id: 'SizjeiwS6suoTExbs'}, {roles: 1})
{ _id: 'SizjeiwS6suoTExbs',
  createdAt: Fri Apr 24 2015 08:26:48 GMT-0600 (MDT),
  services:
   { everything looks fine here }
roles: [] } <- aha!

Let me show you the actual meteor mongo shell  (where one can see the
db.users in mongo)

:meteor_test alex$ meteor mongo
MongoDB shell version: 2.6.7
connecting to: 127.0.0.1:3001/meteor
meteor:PRIMARY> db.users.findOne({_id: 'SizjeiwS6suoTExbs'}, {roles: 1})
{ "_id" : "SizjeiwS6suoTExbs", "roles" : [ ] }
meteor:PRIMARY>


So... i got no roles... :(

**Comment by alanning** [comment]
I'd guess its some quirk of the "meteor shell".  Try putting the `Roles` function calls in your app's startup code and see if it updates the database as expected.

**Comment by elfatherbrown** [comment]
Well... yeah. No tinkering in the "meteor shell" is the lesson to extract here. I just killed the extra role from the db directly and boom, up and running again.

Thanks alanning, its a supperb solution.
