### ISSUE TITLE
Consider Roles + Permissions as security model

### ISSUE THREAD

**Issue by brylie** [alanning/meteor-roles#114]
In the [Meteor Devshop Roles Presentation](https://www.youtube.com/watch?v=ooBEJIirNEo), there was a ['best practices' segment](https://www.youtube.com/watch?feature=player_detailpage&v=ooBEJIirNEo#t=1000). In the 'best practices' it was mentioned that roles should be defined more in terms of permissions than 'job titles'. However, there generally tend to be user classes, and those classes may have clusters of permissions. This is similar to the [Drupal roles/permissions system](https://www.drupal.org/node/120614). 

What are your thoughts on defining a set of user roles (admin, editor, user) and assigning permissions to the user roles (publish, view, edit, delete, ...) as a roles/permissions matrix?

**Comment by brylie** [comment]
This idea might assume some CRUD convention. I.e. many of the permissions, in Drupal at least, follow common patterns:

* can create ...
* can update ...
* can update own ...
* can delete ...
* can delete own ...

**Comment by brylie** [comment]
Additionally, some permissions may be field based. This can be defined at the schema level, as is done in [Mongoose accessibleBy](https://github.com/codedoctor/mongoose-plugins-accessible-by).

**Comment by brylie** [comment]
It is also important to define common patterns for access control. Here are a few common places where access control may be needed:

* Collections (defined in schema?)
  * CRUD
  * Field-level access control
* Publications
* Routes (defined in routes file?)
* Templates
  * Partials
  * Block helpers

**Comment by brylie** [comment]
[ability.js](https://github.com/scottkf/ability-js) has a role/permissions approach, that may be complementary to this idea and package.

**Comment by brylie** [comment]
The [ACL](https://www.npmjs.com/package/acl) module has a similar scope to this idea, incorporating roles as part of an access control policy framework.

**Comment by mitar** [comment]
I do not think this package defined how you use roles. You can also use them as permissions.

**Comment by brylie** [comment]
Right, I am just describing a more explicit model where roles and permissions are plainly distinguishable. This seems like a common pattern for systems with Access Control Lists.

On 13 November 2015 07:10:13 EET, Mitar <notifications@github.com> wrote:
>I do not think this package defined how you use roles. You can also use
>them as permissions.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/alanning/meteor-roles/issues/114#issuecomment-156324489

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by alanning** [comment]
@brylie My apologies for missing this issue and thanks to @mitar for the update.

Thanks for the links to other projects.  Looking forward to reviewing them.

Regarding ACLs, this package does support them in a fashion.  Basically the "group" in roles is actually the "resource" in normal ACL terminology.  (Maybe we should use "resource" instead of "group".)  But we don't support hierarchies yet.  This thread has some more of my thoughts on it:  https://github.com/alanning/meteor-roles/issues/117#issuecomment-133714267

Ultimately my goal for the next major version of this package, roles 2.0, is to improve the design so that others can build on top of it and use roles as a dependency.

The two key packages that I'd like to help others be able to implement are:

* heirarchy of roles/permissions

* scheduled access control

If you have suggestions on how to architect roles 2.0 to help enable this please share!  :-)

**Comment by mitar** [comment]
So I think there is also a case for document-level permissions. Resources can be something in the middle. But for document-level permissions you probably want to store them with documents. Because that can really grow a lot for many documents if you are storing all in one (user) document.

**Comment by brylie** [comment]
@alanning good to hear 2.0 is on the horizon. IMO, in the 2.0 release, there should be a clear API distinction between roles and permissions. That way, developers can write semantic code to define their permissions and assign permissions to roles.

**Comment by mitar** [comment]
I think that it would be in fact better that package does not predefine that. I think that hierarchical roles solve this for you. For example, you can have roles as first level, and then permission as the second. Like:

* `moderators`
  * `deleteComments`
  * `moderateComments`
  * `blockUser`

If you really want naming that, you can always then create a thin layer of abstraction on top.

**Comment by brylie** [comment]
Linguistically, there are two types of phrases in the list you mention. 'moderators' is a noun, or noun phrase, while 'deleteComments' is a verb, or verb phrase. This affects the way we talk about permission/roles systems, and it may be useful to provide similar programming semantics.

E.g.

```JavaScript
Role("moderators").can("deleteComments");
```

**Comment by mitar** [comment]
Yes, that is why I am saying that you can have a thin layer of abstractions on top of this with the semantics you want. Why would we force one semantics on top of this? What about people who prefer roles and capabilities? Roles and processes? Verbs and adverbs? `Verb("read").how("fast")`

**Comment by brylie** [comment]
Yes, I am asking for an abstraction, or user interface, to write roles and permissions in a semantic form. The basic linguistic form is Noun Phrase, Verb Phrase - and this fits nearly all of the examples you provide (adverbs are part of the Verb Phrase).

**Comment by mitar** [comment]
Yes, I think that would be a great package build on top of this one.

**Comment by brylie** [comment]
Alright, cool. What are your suggestions for the package design?

**Comment by mitar** [comment]
So hierarchical roles have been implemented for 2.0 and are available in the v2.0 branch. See the [discussion in README](https://github.com/alanning/meteor-roles/tree/v2.0#permissions-vs-roles--or-whats-in-a-name) about permissions and roles. In short, the proposed way is that you create permission with all UPPER_CASE letters and then you add them as children to "roles" roles. Then you assign users to roles, but in the code you check for PERMISSIONS.

Any feedback is welcome.

I am closing this ticket for now.

**Comment by brylie** [comment]
Alright, thanks for the update. I will continue to learn about the changes in 2.0.

The changes, however, may not improve the API in terms of semantics, and relying on uppercase naming convention is somewhat opaque.

**Comment by brylie** [comment]
My goal here is to discuss a human-friendly API for building permisisons into applications. I have provided examples of human-friendly permissions APIs as part of the process. Semantics are very important in communication and programming as they map directly on to our perception and models of real-world systems.

**Comment by mitar** [comment]
No, uppercase naming is just so that it is easier to discuss it. You can name it anyway. In practice, you should probably use [tap-i18n](https://github.com/TAPevents/tap-i18n) package to translate those constant strings into user-friend translated strings anyway.

**Comment by brylie** [comment]
OK, I am going to re-open this issue with a different title/purpose. Specifically, I think it is important to discuss the API. Please do not close the new issue.
