### ISSUE TITLE
Can't view roles for other users

### ISSUE THREAD

**Issue by tiomat** [alanning/meteor-roles#116]
Hi!

I found that default behavior of this package is showing roles only for current authorised user. 
How can I make admin view, which will be show all role for all users, to get ability to manage this?

Sorry for maybe simple question, but I can't find answer in docs.

**Comment by alanning** [comment]
This is not a roles thing, just a meteor pub/sub thing.

You probably already have a publish / subscribe set up on the users collection for your admin users.  Just need to include the `roles` field in the list of fields that are sent down to the client.

Feel free to follow up if its unclear.

**Comment by tiomat** [comment]
Oh, thanks! 

I have code:
```
  Meteor.publish(null, function() {
    return Meteor.roles.find({})
  });
```
And missed:
```
  Meteor.publish(null, function() {
    return Meteor.users.find({})
  });
```
Now it works perfectly!

**Comment by jhuenges** [comment]
Be careful with publishing **all** data! You might need some checks in the publications to avoid that everyone can see all the users information.

**Comment by alanning** [comment]
Yes!  What @jhuenges said!  You definitely don't want to publish all user data to everyone.  

Hmm, if only there were some easy way to check who should get access...   ;-)

You can see an example of what you should do here:  https://github.com/alanning/meteor-roles/blob/master/examples/mini-pages/server/server.js#L107-L117
