### ISSUE TITLE
Atmosphere readme is stale, likely to repel potential users.

### ISSUE THREAD

**Issue by estaub** [alanning/meteor-roles#124]
The atmosphere readme at https://atmospherejs.com/alanning/roles says:

> Meteor versions 0.5 - 0.9.1.1 are supported (with the exception of 0.9.1). UI-less apps are supported as well.

I'm guessing that only the readme is out of date, not the code itself.

**Comment by alanning** [comment]
Yes, it seems the atmosphere text is out of date. The actual readme here on
github is correct so I'll have to figure out why they are out of sync.

Thanks for mentioning this!

**Comment by newswim** [comment]
Might just need to re-publish to atmosphere.
