### ISSUE TITLE
Blaze Warning on Meteor 1.2

### ISSUE THREAD

**Issue by maartenbusstra** [alanning/meteor-roles#125]
This is kind of a useless warning when using Angular instead of Blaze:
`WARNING: Roles template helpers not registered. Handlebars, UI, or Blaze packages not found`

**Comment by alanning** [comment]
Good point.  What would be the best way to check to see if Angular is being used?

(This will also be an issue for pure React UI's so if you happen to know the proper check for React as well that would be helpful.)

**Comment by maartenbusstra** [comment]
I guess by using weak dependencies on Angular and React, and then checking if they're present on "Package".
