### ISSUE TITLE
Feature request: give option to name the publication 

### ISSUE THREAD

**Issue by davidecantini** [alanning/meteor-roles#127]
As you correctly reported <a href="http://stackoverflow.com/questions/19890817/when-is-the-null-publish-ready/19895939"> here</a> and tested  <a href="https://github.com/alanning/meteor-null-publish-test">here</a>, there's no way (as of Meteor 1.1) to know when subscriptions are ready if the publish has no name.

How about modifying the API to let users provide a name instead of hardcoding null in publish? (leaving the default to null like now, for legacy reasons of course).

Thank you in advance for your attention.

**Comment by alanning** [comment]
Hi @davidecantini,  thanks for the suggestion.  It's certainly a pain point and I appreciate the effort you put in researching this.

The next release of `roles` will change the publication to be named and also have a client-side subscription that will automatically be included.  So existing functionality will be maintained while letting people detect when the sub is ready.

As far as timeframe goes, I hope to put out the next release by the end of Sept. but if not then definitely in Oct.

**Comment by davidecantini** [comment]
Hi @alanning, 
Sounds great. Looking forward to the next release. 
Thanks.
