### ISSUE TITLE
Removing user from group

### ISSUE THREAD

**Issue by stefanve** [alanning/meteor-roles#128]
I used to use groups but decided it was too much of a hassle and skipped it. Now I have problems setting roles for those who used to be in a group since their 'roles' property is a struct rather than an array.

"roles" : { "At9QYYRGG6fzKXtKi" : [ "manager", "editor"] }

without the group, Roles would look like this:
"roles" :  [ "manager", "editor"] 

When I do Roles.addUsersToRoles(userId, arrayOfRoles), then I get the error:

 Exception while invoking method 'customSetRoles' MongoError: Can only apply $pullAll to an array. _id: "d39FqG4EktP5TibDN" has the field roles of non-array type Object

To solve that, I thought I remove the group from them, but that is not possible from what I can see. Teoretically that would be done by removing them from a group, or removing a group, but I do not fins any such command. Is there one?

**Comment by alanning** [comment]
You'll have to modify the user record directly to switch back from using groups.

I'd recommend writing a small script that can be run from the mongo shell:

`$ mongo dbname script.js > out.txt`

script.js would loop through all the users and modify their roles field.  Something like:

```
var users = Meteor.users.find({}, {roles: 1});

users.forEach(function (user) {
  var rolesField = user.roles,
        newRoles = [];

  for (var groups in rolesField) {
    newRoles = newRoles.concat(rolesField[groups]);
  }

  Meteor.users.update({_id: user._id}, {$set: {roles: newRoles}});
});
```

Make sure you test this on non-production data first!

**Comment by stefanve** [comment]
I think it could be a good idea if the documentation could point out that "groups" is a one way street
