### ISSUE TITLE
Syntactic sugar for some method names

### ISSUE THREAD

**Issue by raiyankamal** [alanning/meteor-roles#131]
The functionalities offered by the meteor-roles package can be seen as both roles and permissions but there is only one function `setUserRoles ` to do so. I would like to propose adding another function `allowUserPermission`, this one should be a thin wrapper around the already existing `setUserRoles` method.
Similarly, a thin wrapper `revokeUserPermission` could be placed around `removeUsersFromRoles `.

**Comment by alanning** [comment]
Hi @raiyankamal, thanks for the suggestion.  I'd like to keep the API slim for now so won't be adding the aliases at this time.

But you can do it in your own app pretty easily.  Just add this to a file that is loaded on both the client and server:

```
Roles.allowUserPermission = Roles.setUserRoles;
Roles.revokeUserPermission = Roles.removeUsersFromRoles;
```

One thing to note is that `setUserRoles` will overwrite all roles that the user has.  `addUsersToRoles` may be more equivalent to "allow" in this case.
