### ISSUE TITLE
error when  user  addUsersToRoles

### ISSUE THREAD

**Issue by ahmedrabie** [alanning/meteor-roles#139]
if (Meteor.isServer) {
function creatuser_account(username,email){
 var options = {
      username: username, 
      password: '123456', 
      email:email
    };

Accounts.createUser(options, function (err) {
  if (err) {
    alert(err.reason)
  } else {
 var newUserId = Meteor.userId();
     Roles.addUsersToRoles(newUserId,'member');

  }
});

}
when i try to use this  i get   error like this :
insert failed: MongoError: E11000 duplicate key error index: meteor.roles.$name_1  dup key: { : "member" } undefined
debug.js:43 update failed: Access denied undefined

**Comment by alanning** [comment]
The snippet you provided doesn't compile and I'm having trouble reproducing the error. 

Re-open this ticket once you've got a public reproduction available on github for me to look at.

(Btw, `Accounts.createUser` can't be called on the server with a callback.)

**Comment by ahmedrabie** [comment]
what  i can do now ?  what do you suggest i do ?

**Comment by jhuenges** [comment]
Read [this](http://docs.meteor.com/#/full/accounts_createuser) and change your code. As @alanning said, `Accounts.createUser(options, [callback])` cannot be called on the server if there is a callback. And you currently do have a callback:
```javascript
Accounts.createUser(options, function (err) {
   /* this is the callback function */
   if (err) {
      alert(err.reason)
   } else {
      var newUserId = Meteor.userId();
      Roles.addUsersToRoles(newUserId,'member');
   }
});
```

**Comment by ahmedrabie** [comment]
i need  user id so  only  wat to get it   use  Accounts.createUser in  server  side .
 can you help ? how to get user id from client side

**Comment by alanning** [comment]
Have a look at the first example from this section of the readme:  https://github.com/alanning/meteor-roles/#usage-examples

It shows how to create a user and set permissions on the server.

**Comment by ahmedrabie** [comment]
i know  but  my problem is   creat  user from client user i need  to get   user id  from client side  your  example   in server side

**Comment by alanning** [comment]
You can wrap the server example in a meteor method and call the method from
the client. Just make sure that you are locking it down appropriately for
your app. If anyone may create a user than that's fine. But if only certain
people may create users then you'll need to add checks in the validate user
callback. (Sorry, in mobile but there is an example of that in the read me
too.)

**Comment by ahmedrabie** [comment]
thank you it's work

**Comment by ahmedrabie** [comment]
there is a problem how  return  true   when user is not admin  .
  if (Roles.userIsInRole(Meteor.userId(), 'admin')) {
return  true;
}else{

return false;}

**Comment by jhuenges** [comment]
```javascript
if (!Roles.userIsInRole(Meteor.userId(), 'admin')) {
   return true;
} else {
   return false;
}
```
?

By the way, if you insert  ``` before and after your code example, it is easier to read.

**Comment by A21X** [comment]
@jhuenges & @ahmedrabie  Know it's an old thread, but no one should ever use your code snippet since:
```javascript
!Roles.userIsInRole(Meteor.userId(), 'admin')
```
is already a boolean value!
