### ISSUE TITLE
Shouldn't getGroupsForUser accept an array of roles instead of a singular role?

### ISSUE THREAD

**Issue by ubald** [alanning/meteor-roles#140]
What are your thoughts on this one?

**Comment by alanning** [comment]
`getGroupsForUser` was contributed by a community member and I guess their use case only needed a single role.

Sounds like your use case would benefit from being able to check for multiple roles at once.  Happy to accept a PR (needs to include tests).  Let me know if you'd like help doing the conversion.

Closing this issue for now but feel free to log your PR against it anyways if you want to put one together.

**Comment by mitar** [comment]
This was done as part of v2.0. `getPartitionsForUser` accepts now an array of roles.
