### ISSUE TITLE
Group based functions.

### ISSUE THREAD

**Issue by AlexFrazer** [alanning/meteor-roles#142]
The use case is a page that has a group identifier. Take for example the following URL

```
/guilds/:guild-slug/
```

For this page, I really just want to publish anything to anyone who is in this guild, regardless of what their actual role in the guild is.

```
Meteor.publish('guild', function (slug) {
  if (Roles.userIsInGroup(this.userId, slug)) {
    return Roles.getUsersInGroup(slug);
  } else {
    this.error(new Meteor.Error(403, "Access denied"));
  }
});
```

Some suggestions for methods to add to the api:

```
groups => Mongo.Collection instance
Roles.getUsersInGroup(group)    => all users in group
Roles.userIsInGroup(userId, group) => user belongs to group
Roles.getAllGroups();  => all groups
```

**Comment by alanning** [comment]
The question of whether the roles package should track group membership is an interesting one.  On the one hand, you could say that simply having a blank permission list for a group implies membership.  On the other, tracking membership _in_ a group can be seen as different than what permissions someone has.

This package errs on the side of only tracking the permissions.  This is based on real-world feedback from end users.  It is often nice to be able to add someone to a group and then later decide what permissions you'd like them to have in the group.

So to accomplish your use case, the recommendation is to have a separate field which tracks membership.  This also provides the benefit of being indexable.

Ex:

```
// mongo shell
> db.users.findOne({})
{
  "_id": "foo",
  "guilds": ["1234", "abc", "newGuild"],
  "roles": {
    "1234": ["read", "write"],
    "abc": ["read"],
    "newGuild": []
  }
}
```

**Comment by fly19890211** [comment]
hello, 
i was trying to getUsersInGroup as well. and i did some trick, if the following could help you.
`var allRoles = Roles.getAllRoles().map(function(role) {
        return role.name;
    })`

`var users = Roles.getUsersInRole(allRoles, 'group-name').map(function(user) {
        return user._id;
    })`
