### ISSUE TITLE
Restrict router access to certain roles

### ISSUE THREAD

**Issue by JacobPariseau** [alanning/meteor-roles#144]
There does not seem to be an intuitive way to disallow the router from passing a user into a location they should not be. Am I overlooking something?

**Comment by Maxhodges** [comment]
could do it in onBeforeAction
http://stackoverflow.com/questions/29923007/ironrouter-alanningroles-why-this-role-check-working-randomly

**Comment by alanning** [comment]
Thanks for the link @Maxhodges .  I added an [answer](https://stackoverflow.com/questions/29923007/ironrouter-alanningroles-why-this-role-check-working-randomly/34688511#34688511) which I think will help @JacobPariseau as well so I'm closing this issue for now.  Jacob, in particular please see the examples I link to in the answer but feel free to ask further if you need.
