### ISSUE TITLE
Not checking if userIsInRole()

### ISSUE THREAD

**Issue by mauriciord** [alanning/meteor-roles#147]
Hello, i've included alanning:roles at my project as in Readme, created the users at server/init.js
```javascript
//server/init.js

var users = [
      {name:"Normal User",email:"normal@ehnormal.com.br",roles:[]},
      {name:"Usuario Secreto",email:"mauriciord@me.com",roles:['view-secrets']},
      {name:"Usuario Gerenciador",email:"mauricioreattoduarte@gmail.com",roles:['manage-users']},
      {name:"Mauricio",email:"mauricio@thcm.com.br",roles:['admin']}
    ];

    _.each(users, function (user) {
      var id;

      id = Accounts.createUser({
        email: user.email,
        password: "apple1",
        profile: { name: user.name }
      });

      if (user.roles.length > 0) {
        // Need _id of existing user record so this call must come
        // after `Accounts.createUser` or `Accounts.onCreate`
        // Roles.addUsersToRoles(id, user.roles, 'default-group');
        Meteor.users.update({_id: id}, {$set:{'emails.0.verified': true}});
        console.log("usuario criado");
        Roles.addUsersToRoles(id, user.roles, 'default-group');
        //Roles.addUsersToRoles(id, user.roles);
      }
    });
```
Like said in README too:
```javascript
//server/publish.js
Meteor.publish(null, function (){
  return Meteor.roles.find({})
});
```
But when i try to check User's permission in routes.js: see all [here](https://github.com/mauriciord/thomasicamargo/blob/master/lib/routes.js)
```javascript
// lib/routes.js
var logado = FlowRouter.group({
  name: 'logadoRoutes',
  // se não estiver logado vai para /login
  triggersEnter: [function(context, redirect) {
    console.log('logado grupo');
    if(!Meteor.userId()) {
      FlowRouter.go('login');
    } else {
      return true;
    }
  }]
});

var admin = logado.group({
  prefix: '/admin',
  name: 'adminRoutes',
  triggersEnter: [function(context, redirect) {
    var loggedInUser = Meteor.userId();
    console.log('verificando admin ...');
    if (Roles.userIsInRole(loggedInUser, ['view-secrets', 'admin'], "default-group")) {
      return true;
      console.log('é admin -  rotas');
    }
    console.log('não é admin -  rotas');
    throw new Meteor.Error(403, "Acesso Negado");
  }]
});
```
I'm trying to check if logged user has an admin permission.
I've tried all the ways.
That check returns false, can anyone help me ?
My repository here: [https://github.com/mauriciord/thomasicamargo](https://github.com/mauriciord/thomasicamargo)

Best regards,
Mauricio

**Comment by joejeet** [comment]
Not looked in repo but it looks like Roles subscription may not available yet. Check before your *Roles.userIsInRole condition* if `Roles.subscription.ready()` is ready. And then in your layout/main template you can wait for `Template.subscriptionsReady`.

**Comment by mauriciord** [comment]
Tried and not yet, you can see the [layout](https://github.com/mauriciord/thomasicamargo/blob/master/client/views/layouts/HomeLayout.html) and the [`Roles.subscription.ready()`](https://github.com/mauriciord/thomasicamargo/blob/master/lib/routes.js)

My packages are:
```
meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
blaze-html-templates    # Compile .html files into Meteor Blaze views
session                 # Client-side reactive dictionary for your app
jquery                  # Helpful client-side library
tracker                 # Meteor's client-side reactive programming library

standard-minifiers      # JS/CSS minifiers run for production mode
es5-shim                # ECMAScript 5 compatibility for older browsers.
ecmascript              # Enable ECMAScript2015+ syntax in app code

kadira:flow-router
kadira:blaze-layout
erasaur:meteor-lodash
stolinski:stylus-multi
fortawesome:fontawesome
spiderable
fastclick
raix:handlebar-helpers
aldeed:collection2
aldeed:autoform
accounts-ui
accounts-password
matb33:bootstrap-glyphicons
zimme:active-route
gwendall:auth-client-callbacks
meteortoys:allthings
datariot:ganalytics
check
twbs:bootstrap
less
arillo:flow-router-helpers
alanning:roles
```

Thanks !

**Comment by joejeet** [comment]
There is typo in your layout it's `isInRole` not 'ifInRole'

**Comment by mauriciord** [comment]
Hey @joejeet , thanks !! : )
I changed in layout with `isInRole` as you said, and now it's working.
I was trying to verify the condition on `routes.js` just pressing 'Enter' on the URL of Navigation Bar. localhost:3000/admin, but when i go this route via anchor link, the condition work 100% haha.
I don't know why, i'm new on MeteorJS.

**Comment by joejeet** [comment]
Have mention one mention one small change on your commit.

**Comment by mauriciord** [comment]
I've added a note there, thanks @joejeet 
i used this:

```javascript
if (Roles.subscription.ready()){
      if(Roles.userIsInRole(loggedInUser, ['admin'], 'default-group')){
        return true;
        console.log('é admin -  rotas');
      }
 }
```
but not yet, just navigation via anchor !

**Comment by mauriciord** [comment]
I verified that when i go to page through the URL (navigation bar), the condition `if (Roles.subscription.ready()){` don't work, so does not result the `Roles.userIsInRole(loggedInUser, ['admin'], 'default-group')` because roles subscribe not loaded. If there was a way of load roles subscribe on `route.js`, i could try that condition. How can i load roles subscribe on `routes.js` ?

**Comment by alanning** [comment]
I think the issue is you are doing auth checks in the route but FlowRouter
is not reactive. You need to do your checks in your templates.

I did a talk on how to do this recently at the NY DevShop so keep an eye
out on the meteor YouTube channel. It should be posted soon.

In the meantime check out the flow router guide's section on auth:
https://kadira.io/academy/meteor-routing-guide/content/implementing-auth-logic-and-permissions

And also see this example from the roles repo:
https://github.com/alanning/meteor-roles/tree/master/examples/flow-router-advanced

**Comment by mauriciord** [comment]
If i call `subscriptions` in a route ? Like this:
```javascript
var admin = logado.group({
  prefix: '/admin',
  name: 'adminRoutes',
  subscriptions: function() {
    this.register('roles', Meteor.subscribe('roles'));      
  },
  triggersEnter: [function(context, redirect) {
    var loggedInUser = Meteor.userId();
    console.log('verificando admin ...');
    if (Roles.subscription.ready()){
      console.log('entrou no subscription ready');
      if(Roles.userIsInRole(loggedInUser, ['admin'], 'default-group')){
        return true;
        console.log('é admin -  rotas');
      }
    }else{
      console.log('não entrou no subscription ready');
      if(Roles.userIsInRole(loggedInUser, ['admin'], 'default-group')){
        return true;
        console.log('é admin -  rotas');
      }
    }
    console.log('não é admin -  rotas');
    throw new Meteor.Error(403, "Acesso Negado");
  }]
});
```
I don't know if it is ...`.subscribe('roles')` ...

**Comment by mauriciord** [comment]
I've added useraccounts:bootstrap and checked permission in templates.
Working now ! Thanks @alanning and @joejeet

**Comment by alanning** [comment]
To follow up on this, my talk on FlowRouter Auth is now up on the Meteor YouTube channel:  https://www.youtube.com/watch?v=KK_ua6vxkP4
