### ISSUE TITLE
deleteRole do not check users with roles at Roles.GLOBAL_GROUP

### ISSUE THREAD

**Issue by sampaiodiego** [alanning/meteor-roles#150]
The function docs says:

> Delete an existing role.  Will throw "Role in use" error if any users are currently assigned to the target role.

But if you set a user role using:

`Roles.addUsersToRoles(joesUserId, 'super-admin', Roles.GLOBAL_GROUP)`

You can call with no errors:

`Roles.deleteRole('super-admin')`

**Comment by alanning** [comment]
Thanks for the heads-up.  Global roles are a bit different and it seems we aren't testing that use case properly.

Roles v2.0 is about to land this month so I'd like to revisit this after that.  We may be changing how global roles work.

**Comment by mitar** [comment]
In v2.0 I changed this so that error is not thrown, but users are removed from the role before the role is deleted.

**Comment by mitar** [comment]
Closing this issue in favor of v2.0. If you observe issues with deleting roles in v2.0 please comment. Or if documentation does not match the behavior.
