### ISSUE TITLE
Get All Roles For a Group

### ISSUE THREAD

**Issue by odesey** [alanning/meteor-roles#151]
Is it possible to get all roles for a group? 

So lets say I have many organizations with the role ```admin``` but only some of those organizations have the role ```nice_employee``` I want to be able to allow the "admins" for each "Group" (organization) to add and remove roles that are specific to them and not all that are available to all organizations. Is this possible?

I added a role to a user like this:
```Roles.addUsersToRoles(joesUserId, ['manage-team','schedule-game'], 'manchester-united.com')```

But when I run ```Roles.getAllRoles``` I get back an empty array. I am trying to do this with the autoform package which is turning out to be a bit more complex than I had anticipated.

**Comment by alanning** [comment]
Hi @odesey, did you already figure out a solution to this?

If not, I'd suspect that you aren't publishing the roles to the client.  The readme mentions this but it is easily overlooked.  See the end of [this section](https://github.com/alanning/meteor-roles#changes-to-default-meteor-behavior) for how to publish the roles.
