### ISSUE TITLE
userIsInRole return value is unpredictable is called in flow-router triggersEnter callback

### ISSUE THREAD

**Issue by Firfi** [alanning/meteor-roles#152]
Sample code: 

```
var adminRoutesGroup = FlowRouter.group({
  prefix: '/admin',
  triggersEnter: [
    function(path, redirect) {
      console.warn('Meteor.userId()', Meteor.userId());
      console.warn('Roles.userIsInRole(Meteor.userId(), [admin])', Roles.userIsInRole(Meteor.userId(), ['admin']));
      return !Roles.userIsInRole(Meteor.userId(), ['admin']) ? redirect(....) : null;
    }
  ]
});
```

With same Meteor.userId(), I have `Roles.userIsInRole(Meteor.userId(), ['admin'])` =>  `true` for Chrome and `false` for Firefox or mobile Safari.

**Comment by aardvarkk** [comment]
I'm having a similar issue, it seems? When the server does a hot reload a check fails on a page, but if I manually visit it the check succeeds. It's the exact same query (I've checked), but it returns no results in one case and returns the correct result in another? Could it have something to do with the state of the database while a hot code reload is happening?

**Comment by alanning** [comment]
This is due to the data not being available on the client when the check is performed.  FlowRouter is not reactive so you can not do these kinds of auth checks in the routes like you could with IronRouter.  Instead, you need to do these checks in your templates.

I recently did a presentation about this at DevShop NY.  The video isn't up on the Meteor YouTube channel yet but you can find the slides here:  http://slides.com/alanning55/a-pattern-for-flowrouter-auth/#/

Also be sure to check out the example apps for FlowRouter here:

https://github.com/alanning/meteor-roles/tree/master/examples

**Comment by Siyfion** [comment]
@alanning I know that this isn't exactly "your" issue, rather than a Flow Router design choice, but it is a ***massive*** pain in the ass when you've got a variety of roles. I know that the `triggersEnter` functions aren't reactive, but once the application is loaded, everything is perfectly fine using them in combination with the following reactive code:

``` javascript
// When a login is performed, go to the dashboard
Accounts.onLogin(() => {
  let currentRoute = FlowRouter.current();
  if (currentRoute && currentRoute.route.group.name === 'public') {
    FlowRouter.go('dashboard');
  }
});
// If the user logs out, redirect to the login page
Tracker.autorun(() => {
  if (!Meteor.userId()) {
    FlowRouter.go('login');
  }
});
```

So is there a way to safely "stall" the router until the user has loaded?

**Comment by mitar** [comment]
You could do something like:

```javascript
Tracker.autorun(function () {
  if (!Roles.subscription.ready()) return;

  // do something with flow router
});
```

**Comment by Siyfion** [comment]
@mitar I guess that's the kind of thing I'm on about, it's just a shame that currently, utilizing the `triggersEnter`, it works flawlessly unless they F5 refresh, or for the very first load.

**Comment by mitar** [comment]
Forget my comment, this is probably not the reason. You do not really neeed `Roles.subscription` to be ready for what you are doing.

**Comment by mitar** [comment]
I think the main approach is that you should not be stalling router, but that you should be rendering templates reactivelly base on permissions.

**Comment by Siyfion** [comment]
@mitar well, it's whatever needs to be ready for:
```
authenticatedRoutes.route('/user_management/:_id', {
  name: 'editUser',
  triggersEnter: [Modules.both.routeTriggerFilters.siteAdmin],
  action() {
    BlazeLayout.render('default', { yield: 'userEditor' });
  }
});
```

**Comment by Siyfion** [comment]
@mitar I agree, but the amount of templating-code and extra complexity it adds is a real drawback. Especially as I've got a mixture of Blaze (1.0) and React components currently, with Blaze templates wrapping various top-level React Components.

**Comment by alanning** [comment]
@simon, it's a race condition if you check any data provided by the server
in your flow router routes. The only solution is to either use
template-level checks or use Iron-Router, since it's reactive.

I'm on mobile now so can't reference properly but there are two examples in
the roles repo which shows how to properly check for permissions at the
template-level.

**Comment by Siyfion** [comment]
@alanning / @mitar How can I check for the data not being loaded as opposed to the user not having the role? ie. I want to *redirect* if they don't have the role, just show a "loading" or some such if they haven't loaded the roles as-yet?

**Comment by alanning** [comment]
You'd use meteor's pub/sub ready flag from when you publish your user docs.

On mobile so hard to link but you should be able to find an example of
checking for sub ready in the meteor docs, I think.

**Comment by Siyfion** [comment]
Ah okay, that's easy enough. Thanks!

**Comment by mitar** [comment]
@alanning: Hmmm. In README we have:

> The currently logged-in user's roles field is automatically published to the client.

But where is the code which really does this? I cannot find it?

**Comment by alanning** [comment]
For version 1.x, the "_roles" publish handles that and is found here:
https://github.com/alanning/meteor-roles/blob/master/roles/roles_server.js

The client subscription can be found here:
https://github.com/alanning/meteor-roles/blob/master/roles/client/subscriptions.js

I haven't gone through the v2 code yet though so maybe it's something we
need to add back in?

**Comment by mitar** [comment]
Oh, I thought that is for roles collection. I confused things.

No, this is also in v2.0. I have not changed that.

**Comment by alanning** [comment]
To follow up on this, my talk on FlowRouter Auth is now up on the Meteor YouTube channel:  https://www.youtube.com/watch?v=KK_ua6vxkP4

**Comment by d4nyll** [comment]
If you don't want to defer the checks/redirect to the template, here's an ugly hack:

    // Synchronously blocking everything until Roles is ready
    while(!Roles.subscription.ready()) {}
    
    // Now check if the user is in the role
    if (Roles.userIsInRole(currentUserId, 'admin')) {
        redirect('/admin');
    }

As I said - ugly.

**Comment by mitar** [comment]
Was this tested? Because in JavaScript, busywaiting might not get you anywhere because you have only one execution thread. So there is no free thread which would switch `ready` flag.

**Comment by d4nyll** [comment]
@mitar It works for me, but it's a hack, so I wouldn't use it as a long-term fix.

**Comment by KristerV** [comment]
I used a timeout. works pretty well.

```
function waitForRoles(callback) {
	if (!Roles.subscription.ready()) {
		Meteor.setTimeout(function(){
			 waitForRoles()
		}, 100);
	} else {
		callback()
	}
}

FlowRouter.route('/', {
	action: function(params) {
		waitForRoles(function(){
			// do stuff with Roles
		})
	}
});
```

**Comment by alanning** [comment]
For anyone else reading this, using a timeout is not the recommended approach.  As Arunoda points out in the [FlowRouter docs](https://kadira.io/academy/meteor-routing-guide/content/subscriptions-and-data-management), performing checks that rely on subscription data in the route is an anti-pattern and results in a poor user experience.

For the proper way to do this, please see: 

* https://kadira.io/academy/meteor-routing-guide/content/implementing-auth-logic-and-permissions
* https://github.com/alanning/meteor-roles/tree/master/examples
* https://www.youtube.com/watch?v=KK_ua6vxkP4
