### ISSUE TITLE
Best way to manage roles

### ISSUE THREAD

**Issue by JacobPariseau** [alanning/meteor-roles#156]
I have so far been using roles for two purposes: first to designate user classifications like 'admin', 'moderator', 'anonymous' and so on and second to track which chat rooms the user has access to like 'room-a', 'room-b', etc.

I am now implementing a sort of achievements/awards system and once again the roles package seems perfectly suited for assigning these achievements to users as they meet the requirements. I could continue prefixing titles like 'award-a', 'award-b' but I worry that will still get messy eventually if I keep adding new varieties of roles. Is there an obvious better way to do this?

**Comment by alanning** [comment]
Not sure about an obviously better way but it seems like you are using the roles package in 3 ways:

* user permissions
* chat room membership
* awards

This may be alright.  If it starts feeling "forced" then its probably time to refactor.  :-)

For my own app, we use a separate "channels" field on the user object to track membership.  This grants the additional benefit of being indexable in MongoDB which is important for performance.

Then we use roles "groups" to tie the permissions to channels:

```js
Roles.addUsersToRoles(joesUserId, ['manage-team','schedule-game'], 'manchester-united.com')
Roles.userIsInRole(joesUserId, 'manage-team', 'manchester-united.com')  // => true
```

We don't really have an analogy with awards but I would probably lean towards storing that in a separate field on the user just to keep it clean.  You can certainly cherry-pick code our of the package that might be useful.

**Comment by PankajJatav** [comment]
I suggest you to add two collection that will help you manage user permission.
Like admin have all access.
moderator have room-a access.
anonymous have room-b access.
In collection :
room collection :
{name:'A',id:'1'},
{name:'B',id:'2'}.
so on ...

role collections :
{ name : 'admin', roles ['all']},
{ name : 'moderator', roles [{id:1, read:true , write:false }]},
{ name : 'anonymous', roles [{id:2, read:true , write:true }]},
so on..

room collection allow you add or delete rooms (While deleting  remove room from all roles).
role collection allow you create, edit or delete user roles.
Please if there is any better solution exist let me know.

**Comment by mitar** [comment]
In v2.0 (currently being in development) you can use "partitions" (previously known as groups) to achieve this. You could create three partitions:
 * `user-classification`
 * `rooms`
 * `awards`

Then you could do things like:
* `Roles.userIsInRole(Meteor.userId(), 'admin', 'user-classification')`
* `Roles.userIsInRole(Meteor.userId(), 'room-a', 'rooms')`
* `Roles.userIsInRole(Meteor.userId(), 'award-a', awards')`

Here I assume that awards and user classifications are global and not linked to rooms.

**Comment by mitar** [comment]
Feel free to comment on the ticket if you need more help. I am closing it for now.
