### ISSUE TITLE
Roles and collection-hooks

### ISSUE THREAD

**Issue by mgrivera** [alanning/meteor-roles#166]
Hi, 
Is it possible to apply hooks on roles? 
In particular, whey I try to associate a hook on a rol, as in: 
```javascript
Meteor.roles.before.remove(function (userId, doc) {
    ... 
});
```
I get this error when building: 

 *TypeError: Cannot call method 'remove' of undefined ...* 

Thanks and bye ...

**Comment by alanning** [comment]
It should be possible.  `Meteor.roles` is just a regular collection.  It seems like collection-hooks is not being loaded for some reason.  Is it working for other collections in your app?  Perhaps this is a timing thing and collection-hooks needs to be included after roles in order for it to properly monkey-patch the existing collections?

**Comment by mgrivera** [comment]
Hi @alanning, 

Thanks for your answer! 

Yes, definitely hooks work for my other collections. In fact, when I was trying to assign one hook to roles, I just copied one from another collection and modify it so that it refers to Meteor.roles.  

Could you please suggest something to try loading roles after hooks? 

Thanks again for your reply. By the way, excellent package. Bye ..

**Comment by alanning** [comment]
To load collection-hooks before roles, I think all you have to do is make sure the `matb33:collection-hooks` line is above the `alanning:roles` line in your `.meteor/packages` file.

Please let me know if that works.

**Comment by mgrivera** [comment]
@alanning, excellent. That little change did the trick. Thanks a lot and bye ...
