### ISSUE TITLE
TypeError: Roles.setUserRoles is not a function

### ISSUE THREAD

**Issue by tdhz77** [alanning/meteor-roles#167]
````
setFinancialRole(user,role){
  var loggedInUser = Meteor.user();
  if (!loggedInUser && !Roles.userIsInRole(loggedInUser, ['Automation', 'Financial'])) {
        throw new Meteor.Error(403, "Access denied")
      }
    Roles.setUserRoles(user, role)
},
removeFromRole:function(user,role){
    Roles.removeUsersFromRoles(user,role);
}
````
I'm using this method in a react JSX server/method.jsx file.
Can anybody explain why I'm getting this error?

**Comment by alanning** [comment]
Not sure why you're seeing that but it looks like the Roles package export is not accessible in your JSX file. 

I'd start debugging from there.  See if there are other package exports that you _can_ access in the JSX and see if there's a difference with how the roles package does things.

(Also I think you should check the logic in your IF statement.)

**Comment by mitar** [comment]
No feedback on this one. Closing.

**Comment by tdhz77** [comment]
Yes, I was calling the function and I needed to pass it down to the child prop before I could pass it to the server method. Thank you for pointing me in the right direction.
