### ISSUE TITLE
Install and test 2.0?

### ISSUE THREAD

**Issue by fallenpeace** [alanning/meteor-roles#171]
How do I install and use 2.0 for testing :)

**Comment by mitar** [comment]
The best is to clone the repository into `packages/alanning:roles` in your app. And then inside that directory change to `v2.0` branch.

**Comment by fallenpeace** [comment]
@mitar, I realized that as I finished posting this lol. I got it installed however with the default folder structure I get.

```
$ meteor add alanning:roles

 => Errors while adding packages:

While building package alanning:roles:
error: Symlink cycle detected at examples/flow-router-advanced/packages/alanning:roles
```

I simply removed the examples folder, which I assume is no big deal

**Comment by mitar** [comment]
Yea. Not sure why it detects this.

**Comment by fallenpeace** [comment]
@mitar If it helps, I'm running Meteor 1.3 Beta 5

**Comment by mitar** [comment]
I discovered that this is a regression in Meteor 1.3 in comparison with 1.2 and previous versions: https://github.com/meteor/meteor/issues/6665

**Comment by MuyBien** [comment]
Hi!

I cannot manage adding the V2 package.

I added the version 1 by:
`meteor add alanning:roles`

Then I did :
`mkdir packages`
`cd packages`
`git clone https://github.com/alanning/meteor-roles.git`

**How to know if I am in version 2?**

Thanks for this wonderful package ;)

**Comment by alanning** [comment]
You're almost there.  Once you clone you'll be on the default version of
the repo which is v1.  To get to v2, go into the cloned directory and do
'git checkout <name of v2 branch>'.

Sorry I'm on mobile but I think the branch name is just 'v2.0' so it would
be 'git checkout v2.0'.

**Comment by MuyBien** [comment]
Hi alanning!
Thanks, I did the checkout and it works. Now I suppose I am on V2 branch...
How to be sure? Is there a meteor command to get a package version? Or maybe using GLOBAL_GROUP will raise an error from the V2 package?

Thanks!

**Comment by MuyBien** [comment]
Well, apparently there is no way to check throught Meteor a package version...
In the `.meteor/versions` I have alanning:roles@1...

I don't know if the version fiile will be updated to V2 or if it's transparent for Meteor with local package. Maybe by making something impossible with V2 in the code, will proove me that I am with V2 version ^^

**Comment by alanning** [comment]
The easiest way to check is probably through the browser console.  Just
pull up the roles script (running in dev mode it should be un-minified) and
see if it matches the v2 code in your packages directory.

We should probably add a version number...

**Comment by MuyBien** [comment]
Well, if I look into the JS file in my browser, I see 

```
  /**                                                                                                              // 42
   * Used as a global group (now scope) name. Not used anymore.                                                    // 43
   *                                                                                                               // 44
   * @property GLOBAL_GROUP                                                                                        // 45
   * @static                                                                                                       // 46
   * @deprecated                                                                                                   // 47
   */                                                                                                              // 48
  GLOBAL_GROUP: null, 
```

So I think I can say that I'm using the V2? :)
Thanks.
