### ISSUE TITLE
[v2.0] Index error when migrating 

### ISSUE THREAD

**Issue by sveinburne** [alanning/meteor-roles#174]
In my mongodb console : `db.roles.getIndexes()` prints

``` json
[
	{
		"v" : 1,
		"key" : {
			"_id" : 1
		},
		"name" : "_id_",
		"ns" : "admin.roles"
	},
	{
		"v" : 1,
		"unique" : true,
		"key" : {
			"name" : 1
		},
		"name" : "name_1",
		"ns" : "admin.roles"
	}
]
```
This prompt an error at meteor startup : `MongoError: E11000 duplicate key error index: admin.roles.$name_1 dup key: { : null }` because field `name` isn't used anymore in v2.

This error is triggered despite the running of `Package['alanning:roles'].Roles._forwardMigrate()` from the meteor shell. 

Had to run `db.roles.dropIndex("name_1")` from the mongo shell!
Hope this helps, cheers :)

**Comment by mitar** [comment]
Ah, yes, we should probably drop old indexes in `Roles._forwardMigrate`. Thanks for reporting this.
