### ISSUE TITLE
Sets of permissions 

### ISSUE THREAD

**Issue by servermeta** [alanning/meteor-roles#188]
Hi guys,

I'm porting a big Java App to meteor, and I'm thinking about what is the best way to port the authorization logic.

I'm used to a very granular permission list, with wildcards and automatically generated permissions. for example:

`Roles.addUsersToRoles(joesUserId, ['manage-team','schedule-game'], 'manchester-united')`

would become: 

`Roles.addUsersToRoles(joesUserId, ['manchester-united.team.manage','manchester-united.team.schedule-game'])`

Each action would have its own permission, and permissions would be automatically created when a specific object is casted. For example if I create a new team _soccerTeam_ then the permissions _soccerTeam.team.manage_ would be automatically created, and there would be a wild card like _soccerTeam.*_ to specify all permissions of a given object.

Obviously this way you will create hundreds of permissions, but to solve this sets of permissions are created, like the set Admin has everything, the set Manager has manage rights over all team, etc... 

I think I can implement all this, but I don't want to reinvent the wheel.

**Is there a way to create sets of permissions which contain a number of other permissions?**

**Comment by mitar** [comment]
You should try the v2.0 branch which has this feature.

**Comment by mitar** [comment]
Closing in favor of #165.
