### ISSUE TITLE
Add method that replace old roles by new roles

### ISSUE THREAD

**Issue by HatemJerbi** [alanning/meteor-roles#197]
Take the example when we have a form where admin assign roles to specific user by group of check box.
the method Roles.addUsersToRoles can't handle this situation because it add new assigned roles and didn't delete unassigned roles.
thxs

**Comment by mitar** [comment]
You should use `setUserRoles`.

**Comment by HatemJerbi** [comment]
typo: i mean Roles.setUserRoles can't handle this situation

**Comment by mitar** [comment]
@HatemJerbi: Why you closed this ticket now? Was the issue resolved for you?

**Comment by HatemJerbi** [comment]
sorry mitar it was my fault, there is no problem with your setUserRoles method.

Best regards

**Comment by mitar** [comment]
I am glad it has been resolved.
