### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by karolselak** [alanning/meteor-roles#210]
I cannot use any group, because every time I receive these errors:

TypeError: Cannot read property 'indexOf' of undefined
I20160827-23:48:40.094(2)?     at strContains (packages/alanning_roles/roles_common.js:713:1)
I20160827-23:48:40.095(2)?     at packages/alanning_roles/roles_common.js:708:1
I20160827-23:48:40.095(2)?     at Array.some (native)
I20160827-23:48:40.096(2)?     at Function._.some._.any (packages/underscore/underscore.js:233:1)
I20160827-23:48:40.098(2)?     at isMongoMixError (packages/alanning_roles/roles_common.js:707:1)
I20160827-23:48:40.098(2)?     at Object._.extend._updateUserRoles (packages/alanning_roles/roles_common.js:686:1)
I20160827-23:48:40.098(2)?     at Object._.extend.addUsersToRoles (packages/alanning_roles/roles_common.js:145:1)
I20160827-23:48:40.099(2)?     at [object Object].addUsersToRoles (imports/mods/User/UserMethods.js:9:13)
I20160827-23:48:40.100(2)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
I20160827-23:48:40.100(2)?     at packages/ddp-server/livedata_server.js:711:19

Any idea what is it?

**Comment by mitar** [comment]
Please use the latest master branch and see if it resolves your issue.

**Comment by karolselak** [comment]
Hm, maybe that's stupid, but I have problem with doing this. I pulled repo to package/meteor-roles folder, but I don't know how to add it to project. Before "meteor add alanning:roles" official package is downloading.

**Comment by mitar** [comment]
You have to put it into `packages/alanning:roles`.

**Comment by karolselak** [comment]
Okay, it works, but it takes time until I find out that I must rename the roles folder, not general meteor-roles ;] Thanks for help! I have another problem now, but that's for another issue.
