### ISSUE TITLE
Usage with FlowRouter.triggers

### ISSUE THREAD

**Issue by Netherdrake** [alanning/meteor-roles#220]
I would like to do this:
```
FlowRouter.triggers.enter([
    function (context, redirect) {
        if (!Meteor.userId()) {
            FlowRouter.go('home');
        }
        if (!Roles.userIsInRole(Meteor.userId(), 'admin')) {
            console.log(Roles.userIsInRole(Meteor.userId(), 'admin'))
            FlowRouter.go('home');
        }
    }
]);
```

However `Roles.userIsInRole(Meteor.userId(), 'admin')` always returns `false` when called from  FlowRouter.triggers. It does return `true` when called from browser console.

Any ideas for how could I achieve this?

**Comment by jhuenges** [comment]
This doesnt work because Meteor.user might not be available or the Roles collection is not available because the subscription did not finish yet. 

Maybe [this article](https://kadira.io/academy/meteor-routing-guide/content/implementing-auth-logic-and-permissions) can help.

**Comment by Netherdrake** [comment]
There is a solution on the bottom of [this post](https://medium.com/@satyavh/using-flow-router-for-authentication-ba7bb2644f42#.d2cr5ff0e) that seems to work.
