### ISSUE TITLE
createRole throws syntax error

### ISSUE THREAD

**Issue by msolters** [alanning/meteor-roles#224]
Whenever I run `Roles.createRole` I get the following error output:

```
W20170107-03:48:11.734(-5)? (STDERR) TypeError: Cannot read property 'match' of undefined
W20170107-03:48:11.734(-5)? (STDERR)     at Object._.extend.createRole (packages/alanning_roles.js:156:20)
```

I think you need to check for the existence of both `e && e.err` before executing a `.match` test on `e.err`.

**Comment by mitar** [comment]
I think this was fixed in 79250d651613fb9868a0c5b1b343f63294e32c61.

**Comment by msolters** [comment]
Is this change published?

**Comment by mitar** [comment]
I do not think so.
