### ISSUE TITLE
Can't append to array using string field name

### ISSUE THREAD

**Issue by michalmielczynski** [alanning/meteor-roles#226]
Hey everyone,

I'm not sure if it's my fault or some meteor-roles incompatibility with new Meteor/Mongo.

While trying to execute:
`Roles.addUsersToRoles(Meteor.userId(), 'owner', 'example.org');`

The last part (group parameter) causes an error (it works when last parameter is not given):

`
"Meteor.Error"
message: "MinimongoError: can't append to array using string field name [example_org] [409]"
`

Any idea what's wrong? Thanks in advance!

**Comment by michalmielczynski** [comment]
Bit of debugging - seems that error is thrown in allaning_roles.js package at block 745 - 767:
`
 try {
      if (Meteor.isClient) {
        // On client, iterate over each user to fulfill Meteor's 
        // 'one update per ID' policy
        _.each(users, function (user) {
          Meteor.users.update({_id: user}, update)
        })
      } else {
        // On the server we can use MongoDB's $in operator for 
        // better performance
        Meteor.users.update(
          {_id: {$in: users}},
          update,
          {multi: true})
      }
    }
    catch (ex) {
      if (ex.name === 'MongoError' && isMongoMixError(ex.err)) {
        throw new Error (mixingGroupAndNonGroupErrorMsg)
      }

      throw ex
    }
`

**Comment by alanning** [comment]
I would guess that you were originally using the non-group version for that user?  If you take a look at this section of the readme you can see the difference in database record structure depending on how you first set roles on that user:

https://github.com/alanning/meteor-roles#roles-changes

Have a look at the user's record and see if it is just a straight array.  If so, you'll need to convert it to the other, object, format before using the "group" style of api calls.

**Comment by michalmielczynski** [comment]
Gosh, of course.
I was dropping roles collection, thinking that would reset groups behavior - but clearly the problem lays in user.roles structure. 

Thanks for solution! I was able to clean up unwanted straight arrays, now everything works as expected. 
Perhaps some wrapper to avoid storing 'non-group' roles will be time saver, but I guess this is something I can take care on my project side. 

Thanks again!

**Comment by alanning** [comment]
Glad you got it working!  Just to follow up, please have a look at the [v2 branch](https://github.com/alanning/meteor-roles/tree/v2.0) as it has a new structure which avoids this issue and also allows indexing of roles data, which improves performance of some types of queries.

**Comment by michalmielczynski** [comment]
Thanks for pointing that out.  I know it's probably out of topic, but... how would I install 2.0? 
(I got current version simply by adding alanning:roles in meteor/packages file)

**Comment by alanning** [comment]
To use v2.0, you'd download the repo to your local meteor `/packages`
directory.  Meteor will use the local version before using any others.  So
for example in our app, the resulting directory would look like:

`app/packages/roles`
