### ISSUE TITLE
Which version to use?

### ISSUE THREAD

**Issue by pmcochrane** [alanning/meteor-roles#238]
Starting a large application and wondering which version I should use with meteor 1.4.

Should I stick with the default or go for version 2 which i believe is not completely finished yet? I am also unsure of the status of the npm version although I am not fussed about this for now.

**Comment by alanning** [comment]
If you don't have any packages that depend on Roles v1, then I'd suggest using v2.  It's stable and easy enough to add, just do the normal `meteor add roles` but then clone the v2 branch into your packages directory.  Meteor will use the local version.

The npm version is useful when you have code that you've ported from Meteor to something like Lambda.  We are still on Roles v1 and use the npm version so we can share the auth code in our lambda func and our main meteor app.

**Comment by pmcochrane** [comment]
Which packages directory do you mean? I don't have any local packages at present. I can only find a package folder in my .meteor/.local/build folder which is ignored from my git repo.

Am I right in thinking if I create a packages folder in the root of my app and clone V2 into there it would work?

**Comment by alanning** [comment]
Yep, that's exactly it.  Create a new `packages` directory in your main app dir.

**Comment by pmcochrane** [comment]
Thank you
