### ISSUE TITLE
How to remove all user roles in a group?

### ISSUE THREAD

**Issue by MuyBien** [alanning/meteor-roles#243]
Hi!
I have several groups named for example: 'soccer', 'volleyball', 'waterpolo'...
In each group, you can have one of 3 different roles: 'admin', 'captain', 'player'.
I have a method to set a role to a user within a group, but I don't know the good method to remove all others roles before adding the new one. (I'm using the V2 package)

Removing one by one all roles (even if user do not have it)
```
Roles.removeUsersFromRoles( userID, 'admin', group );
Roles.removeUsersFromRoles( userID, 'captain', group );
Roles.removeUsersFromRoles( userID, 'player', group );
Roles.addUsersToRoles( userID, newRole, group );
```

Using setRole (working with groups?)
```
Roles.setUserRoles( userID,  newRole, group );
```

Thanks!

**Comment by MuyBien** [comment]
`Roles.setUserRoles( userID,  newRole, group );`

seems to do the trick :)

**Comment by vijaymca** [comment]
The below is the best page to visit remove roles from SharePoint group. 
[https://github.com/SharePoint/PnP-PowerShell/blob/master/Documentation/SetPnPGroupPermissions.md](https://github.com/SharePoint/PnP-PowerShell/blob/master/Documentation/SetPnPGroupPermissions.md)

But here I want to know if I want to remove all Roles. How to do .

Please help me
