### ISSUE TITLE
Import Roles with ES6 Syntax?

### ISSUE THREAD

**Issue by joncursi** [alanning/meteor-roles#251]
Is it possible to import the `Roles` global with ES6 import syntax? This request was also mentioned in https://github.com/alanning/meteor-roles/issues/165#issuecomment-211817551

**Comment by joncursi** [comment]
Looks like this works, even though it is undocumented:

```jsx
import { Roles } from 'meteor/alanning:roles';
```

**Comment by mitar** [comment]
This is a normal Meteor importing of Meteor packages.
