### ISSUE TITLE
Roles bypassing allow/deny rules

### ISSUE THREAD

**Issue by ghost** [alanning/meteor-roles#41]
**To Test**

+ Create some roles and a group (as usual) in a new meteor project with the roles package
+ Create a new user and assign that user to a role within the group (as usual)
+ Create allow rules for insert/update/delete (just return true for each)
+ Create a deny rule that disallows a user from updating his own role for that group:

```javascript
Meteor.users.deny({
    // disallow users making themselves admins
    update: function(userId, doc, fields, modifier) {
      return _.contains(_.values(_.find(modifier, 'roles.somegroup')), 'admin')
    }
  })
```

+ In Chrome Dev Tools, try making yourself an admin via minimongo:

```javascript
Meteor.users.update({ _id: "someID" }, { $addToSet: { 'roles.somegroup': 'admin' } })
```

+ Verify that this fails as expected
+ In Chrome Dev Tools, try making yourself an admin via Roles.addUserToRoles:

```javascript
Roles.addUsersToRoles(Meteor.user(), 'admin', 'somegroup')
```

+ Verify that you get `insert failed: Access denied ` in CDT
+ Go to mrt mongo shell and find your user (or inspect your user object in CDT with `Meteor.user()`)
+ Verify that the user _has_ been updated with the role, after all

This _may_ be related to the use of Meteor methods, as per the [Meteor docs](http://docs.meteor.com/#allow):

>Server code is trusted and isn't subject to allow and deny restrictions. That includes methods that are called with Meteor.call — they are expected to do their own access checking rather than relying on allow and deny.

**Comment by mitar** [comment]
Use of allow/deny rules is being slowly deprecated in Meteor exactly because of such issues where it is really hard to create good rules for all cases.

In practice, you should probably not allow any modifications to `roles` field at all through allow/deny rules. And create a Meteor method which calls `addUsersToRoles` with your change, after you validate anything. So what I would suggest is that you do:

```javascript
Meteor.users.deny({
  update: function(userId, doc, fields, modifier) {
    return _.contains(fields, 'rules');
  }
});

Meteor.methods({
  addUserToRole: function (userId, role, partition) {
    check(userId, String);
    check(role, String);
    check(partition, String);

    if (!this.userId || !Roles.userIsInRole(this.userId, 'admin', 'vonvo')) throw new Meteor.Error('unauthorized', "Unauthorized.");
    if (this.userId === userId) throw new Meteor.Error('unauthorized', "Unauthorized.");

    Roles.addUsersToRoles(userId, role, partition);
  }
});
```

**Comment by lnmunhoz** [comment]
@alanning How do I create `allow/deny` rules for the `roles` collection? In my app I' am able to call `addUsersToRole` from the console and get an update access denied from my users collection, but the role if does not exists is inserted.
