### ISSUE TITLE
Roles -> Permissions

### ISSUE THREAD

**Issue by sclausen** [alanning/meteor-roles#42]
Hi, this isn't a real issue, its more an idea. Wouldn't it be awesome, if you could attach permissions to roles and check them on server/client like `Roles.isPermitted(loggedInUser, "admin:users:write");` instead of `Roles.userIsInRole(loggedInUser, ['user-manager'])`. I would suggest a permission system like [Apache Shiro](https://shiro.apache.org/permissions.html).
This way, you could manage what e.g. the admin-user or user-manager can do apart of  the role. 

Therefore you can change the meaning of being in a role and don't have to change every users roles if features of your app change in future.

**Comment by Siyfion** [comment]
I would also agree that some form of hierarchical roles/permissions would be a great feature to have.
