### ISSUE TITLE
Roles is not work with meteor 0.9.1.1

### ISSUE THREAD

**Issue by zakirarrayiq** [alanning/meteor-roles#55]
I create a simple application with 

meteor create test-roles 
cd test-roles
meteor add alanning:roles 
meteor 

When I access the web page I get in the console

WARNING: Roles template helpers not registered. Handlebars or UI package not found

What do I need to initialize Meteor.ui?

**Comment by CaptainChainsaw** [comment]
Looks like this is still an issue.  I'm getting it on Meteor v1.2.0.1.  I've tried removing and adding the package but that didn't work.  I've also installed the patch to fix the "Exception in template helper: ReferenceError: Match is not defined " issue.

alanning:roles                     1.2.13+ Authorization package for Meteor

Anyone else still getting this issue?  Any idea how to fix this?

**Comment by alanning** [comment]
Hi @CaptainChainsaw,

I just tried creating a new Meteor 1.2.0.1 app and adding roles and it seems to work.  I don't see any errors in the console when testing with latest Chrome desktop.  Could you try the following steps and see if your results match mine, please?


```
kaia2:~$ cd tmp
kaia2:~/tmp$ meteor create foo3
Created a new Meteor app in 'foo3'.

To run your new app:
  cd foo3
  meteor

If you are new to Meteor, try some of the learning resources here:
  https://www.meteor.com/learn

kaia2:~/tmp$ cd foo3
kaia2:~/tmp/foo3$ meteor add alanning:roles

Changes to your project's package version selections:

accounts-base          added, version 1.2.1
alanning:roles         added, version 1.2.13
ddp-rate-limiter       added, version 1.0.0
localstorage           added, version 1.0.5
rate-limit             added, version 1.0.0
service-configuration  added, version 1.0.5


alanning:roles: Role-based authorization

kaia2:~/tmp/foo3$ meteor
[[[[[ ~/tmp/foo3 ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
I20150928-13:28:54.066(-4)? ** You've set up some data subscriptions with Meteor.publish(), but
I20150928-13:28:54.067(-4)? ** you still have autopublish turned on. Because autopublish is still
I20150928-13:28:54.068(-4)? ** on, your Meteor.publish() calls won't have much effect. All data
I20150928-13:28:54.068(-4)? ** will still be sent to all clients.
I20150928-13:28:54.071(-4)? **
I20150928-13:28:54.071(-4)? ** Turn off autopublish by removing the autopublish package:
I20150928-13:28:54.071(-4)? **
I20150928-13:28:54.071(-4)? **   $ meteor remove autopublish
I20150928-13:28:54.072(-4)? **
I20150928-13:28:54.072(-4)? ** .. and make sure you have Meteor.publish() and Meteor.subscribe() calls
I20150928-13:28:54.072(-4)? ** for each collection that you want clients to see.
I20150928-13:28:54.072(-4)?
^C
kaia2:~/tmp/foo3$ meteor --version
Meteor 1.2.0.1
```

**Comment by CaptainChainsaw** [comment]
Hey,

challett released a new patch that sorted this:

https://github.com/challett/meteor-roles/tree/challett-patch-4

Cheers :)

**Comment by alanning** [comment]
Cool!  Thanks for the pointer.

**Comment by CaptainChainsaw** [comment]
You're welcome :)
