### ISSUE TITLE
Roles.userIsInRole returns false in onBeforeAction

### ISSUE THREAD

**Issue by aldeed** [alanning/meteor-roles#61]
Updated to latest iron:router and latest alanning:roles and Meteor 0.9.3, and now `Roles.userIsInRole` does not seem to work within a route's `onBeforeAction`.

```js
this.route('admin', {
    onBeforeAction: function (pause) {
      if (!Roles.userIsInRole(Meteor.userId(), 'admin')) {
        console.log(Roles.userIsInRole(Meteor.userId(), 'admin'), Meteor.userId());
        this.redirect("home");
      }
    }
  });
```

I can see from the console.log that the user ID is correct, but `userIsInRole` is returning false. However, after it redirects, I can enter `Roles.userIsInRole(Meteor.userId(), 'admin')` in the browser console and it prints `true`.

So it seems like the roles are not being correctly determined until after `onBeforeAction` runs. Possibly I need to `waitOn` the subscription to the `roles` field, but I don't think I had to do that before.

**Comment by rhyslbw** [comment]
This appears to be resolved now

**Comment by jhuenges** [comment]
@rhyslbw what versions of the roles package and iron router are you using?

**Comment by rhyslbw** [comment]
@jhuenges 
Meteor 1.0.3.1
iron:router 1.0.7
alanning:roles 1.2.13

I haven't actually tested this in isolation, and there is probably a long enough delay in my case to hide the problem.

**Comment by jhuenges** [comment]
Thanks, I ll check it out!

**Comment by leebenson** [comment]
Try changing the doc's example server-side publication to:

```
Meteor.publish('roles', function (){
    return Meteor.roles.find({});
});
```

And then client-side, in Iron Router's `waitOn()`...

```
return Meteor.subscribe('roles');
```

That should wait for the full role list, so `Roles.userIsInRole` works correctly in `onBeforeAction()`

**Comment by aldeed** [comment]
@leebenson, it still won't be correct unless [this subscription](https://github.com/alanning/meteor-roles/blob/master/roles/roles_server.js#L20-L25) is ready. So that publication should be named and the client sub handle should be exported. Yes, we could publish the roles field in a separate pub/sub, but that seems inefficient if the roles pkg is already publishing it.

**Comment by leebenson** [comment]
@aldeed I see, didn't realise this was already explicitly published. For sure it needs naming to play nicely with packages that need to wait for subscriptions. Simple oneline fix. @alanning ?

**Comment by leebenson** [comment]
Created pull request #88

**Comment by juliomac** [comment]
The pub/sub solution from @leebenson also worked for me. Thanks for it!

As for an up-to-date example for usage with iron-router, that would definitely be a good think. Meteor is evolving so quickly that it is like shooting on a moving target. None of the examples here or on StackHolder worked for me. I tested with this.pause(), render() or redirect() and finally got one working with Router.go(). Hope this helps someone else:

    Router.route('/Client/Admin',
      {
        name: 'Admin',
        template: 'Admin',
        layoutTemplate:"layoutWithoutNav" ,
        onBeforeAction: function() {
          if (!(Meteor.userId())) {
            console.log("It is not logged-in");
            Router.go('atSignIn');
          }
          else if (!(Roles.userIsInRole(Meteor.userId(),['Admin']))){
              alert("need to be an Admin");
              console.log("Not an Admin");
              Router.go('home');
            }
              else this.next();
        }

**Comment by alanning** [comment]
Thanks @juliomac.  I did add both an [iron-router](https://github.com/alanning/meteor-roles/tree/master/examples/iron-router) and [flow-router](https://github.com/alanning/meteor-roles/tree/master/examples/flow-router) example recently but they are pretty simple so I don't think they run into this problem.  Happy to accept updates that make the examples more realistic.

I'll be consolidating PRs and should be able to release a new version in around a month that will include Lee's PR.  I'm also working on the design of roles 2.0 so if you have any requests, please open a new issue so we can discuss.
