### ISSUE TITLE
Roles.getGroupsForUser() returns empty array for all except current user.

### ISSUE THREAD

**Issue by benstr** [alanning/meteor-roles#68]
I am building an administrator UI for my app. THe admins would like to ability to see which groups a user is part of and then edit them. First thing is first, list the current groups a user is part of.

I have all the Users published. Through a helper (and directly in the console) when I run `Roles.getRolesForUser('some_user_id')` I get an empty array ~~except for the current user, they get a full list of roles~~.

But if I run `Roles.getUsersInRole('edit_users')` I a full list of users. 

Am I missing somewhere or is this intended or a bug?

I can write something to iterate over each user object and pull the roles, but that is less eloquent than using your API.

**Comment by sday** [comment]
Agreed, docs need a bit more.  Roles.getRolesForUser(Meteor.user()) returned an empty list.  Roles.getRolesForUser(Meteor.user(),'admin') returned the list of roles for specified user in the admin group.  How would I get a list of all roles in all groups for a user?

**Comment by SageHarvey** [comment]
@benstr Sorry for the necropost but I'm currently banging my head against the wall trying to come up with a basic user admin page.  I can get a list of all the users (and the roles currently assigned to each user), and a list of all the roles but can't figure out how to mesh them together.

If you had any success doing so, would you mind sharing what you did?

**Comment by alanning** [comment]
@SageHarvey, can you describe what your goal is?  I may be able to help but sounds like you already have all the pieces so not sure what's left.

**Comment by SageHarvey** [comment]
Hi @alanning, what I'm trying to achieve is a simple control panel that lists all the users in one column and all the available roles in a second column as names with checkboxes, with the roles currently assigned to the user checked off and the table itself allowing live updates to the roles assigned to a user.

Here's how I'm getting the users and roles:
```javascript
if(Meteor.isServer) {
  Meteor.publish("userList", function() {
    return Meteor.users.find({}, {fields: {username: 1, profile: 1, roles: 1}});
  });
  Meteor.publish("allRoles", function(){
    return Roles.getAllRoles();
  });
}
```
And my templates:
```html
<template name="userList">
  {{#each allUsers}}
    <tr>
      <td>{{username}}</td>
      <input type="hidden" id="roles_{{username}}" value="{{userRoles}}">
      <td>
        {{> listRoles}}
      </td>
    </tr>
  {{/each}}
</template>

<template name="listRoles">
  {{#each allRoles}}
    <input type="checkbox" name="roles" value="{{name}}">{{name}}
  {{/each}}
</template>
```

**Comment by alanning** [comment]
Do you know about the `Meteor.roles` collection?  It has all the
roles/permissions that have been added to user accounts so that may be what
you are looking for.

If not, can you make a quick back-of-the-napkin drawing and post it
somewhere please?  It will help me understand your target UI.

**Comment by SageHarvey** [comment]
Hmm... that sounds like what I may need.  Let me dig into the Meteor.roles collection a bit.

Here's the rough UI I was going for:
![UI](http://imgur.com/1zinOJU.png)

**Comment by SageHarvey** [comment]
Meteor.roles didn't help me much.  It was the same information I was getting from Roles.getAllRoles().

It doesn't seem like it should be this difficult and I'm guessing my newness to Meteor is making me miss something obvious.

**Comment by alanning** [comment]
Hmm, for the UI that you want to make, you actually need two separate things:

1. a list of all the permissions that the user may have
2. a list of all the permissions that the user currently has

The second one you know how to get.  

The first one should actually not come from the Roles package.  It can either live in your code or you can make another collection in your db just for it.

In our app we just have the list defined in the code.  Simplest but requires code changes when permissions are added or renamed.

Keep in mind that you may eventually want to have different subsets of permissions for different types of users.  For example we have two separate sets of permissions depending on whether a user is a member of a public safety agency or not.

**Comment by mitar** [comment]
In v2.0 branch you can use `anyPartition` option to get roles for an user in any partition (previously known as groups):

```javascript
Roles.getRolesForUser(userId, {anyPartition: true});
```

You do probably want to set `fullObjects` to `true` as well, otherwise you will not know from which partition which returned role is coming from.

**Comment by mitar** [comment]
Although this will not help you much with the UI above. For the list of available roles for all users you should probably just consult the `Meteor.roles` collection. This package stores all roles you created (with v2.0 you have to explicitly create roles).
