### ISSUE TITLE
[Feature request] Returning all users in role

### ISSUE THREAD

**Issue by msamoylov** [alanning/meteor-roles#78]
Use case: A new entry is added to the collection and we need to alert admins about that. We need to select all admins and send them an email message.

**Comment by msamoylov** [comment]
RTFM first http://alanning.github.io/meteor-roles/classes/Roles.html#method_getUsersInRole

**Comment by alanning** [comment]
:-)  Glad you found it.  There's also a pull request that we'll merge in soon that will allow you to select which fields to return:  https://github.com/alanning/meteor-roles/pull/77
