### ISSUE TITLE
Roles.addUsersToRoles doesn't automatically add roles to in-code user object

### ISSUE THREAD

**Issue by vaughnkoch** [alanning/meteor-roles#79]
When calling addUsersToRoles, the given user object has roles added to it in Mongo, but those roles aren't auto-added to the user object. A workaround is to reload the user object from the db, which is less efficient.

Repro
Let me know if you want me to add additional instrumentation.
var user = Meteor.users.findOne(userId); // userId supplied earlier in code
console.log('adding user');

Roles.addUsersToRoles(user, ['foobar']);
console.log(user.roles);

user = Meteor.users.findOne(userId);
console.log(user.roles);

=> Meteor server restarted
I20150120-13:28:55.307(-8)? adding user
I20150120-13:28:55.325(-8)? undefined
I20150120-13:28:55.328(-8)? [ 'foobar' ]

You can ensure that the data's there by reloading the user object, but shouldn't it work without requiring another mongo round-trip? A simple solution would just be to set the roles object on the user obj directly within addUsersToRoles.

**Comment by alanning** [comment]
Hi @vaughnkoch, thanks for making a new issue for this.  I think it would be nice to have it behave as you suggest and may also help with the confusion users see around [`Accounts.onCreateUser`](http://stackoverflow.com/questions/22649600/unable-to-add-roles-to-user-with-meteor-using-roles-package/22650399#22650399).  

Can you help think through / write up a few different use cases, such as where `onCreateUser` is involved and see if you can come up with any potential problems there, please?

**Comment by vaughnkoch** [comment]
Well, a related issue is that you can't add roles to the user object within onCreateUser because at that point, the document hasn't been inserted into the DB.

Maybe addUsersToRoles could take a param that indicates it's only adding to the user document and not to the db.  That way it could be used inside onCreateUser and the db would get the record when the function completes.

What really should exist on Meteor's side is a way to hook into user pre AND post creation.  Something like Accounts.onBeforeCreateUser() and Accounts.onAfterCreateUser().

**Comment by alanning** [comment]
The `on` vs. `after` hooks would be nice.  Other frameworks I've used would do something like:

`onCreateUser` = before
`afterCreateUser` = after

Having a option to update the object may be best.  We could automatically update the object only when there is no `_id` field... that would take care of the case of `onCreateUser`.

If there is an `_id`, not sure what we should do.  Would be nice to update the object too but then we'd have to check that the db update completes successfully to ensure consistency as having it silently be inconsistent would be very bad.  Not sure how to do that at the moment, having a separate `findOne` is not worth it. 

Looks like Meteor's [collection `update`](http://docs.meteor.com/#/full/update) returns the number of affected records but not sure if that's enough as MongoDB won't actually modify the record if it already matches the end result.  On the shell you can see nMatched vs nModified, which are not always the same...

**Comment by mitar** [comment]
In v2.0 branch (currently in development), `addUsersToRoles` logic is relatively complex and uses multiple queries against the database to make role hierarchy work. From user object only `_id` is used, everything else is ignored. To make it update the user object, the easiest way in fact is to reload the object. Then you can be assured that it really corresponds to the state in the database. Now, I think that if somebody needs that they can just reload it outside of the `addUsersToRoles` and we should not be reloading the object inside. Duplicating the logic to be able to update user object is for me premature optimization. Editing roles is a very infrequent operation. That one extra read query does not seem to me worth making this important function even more complex. Please provide some benchmarks that this change is really needed. Until then I am closing this ticket.
