### ISSUE TITLE
How to get count for all users in a particular role?

### ISSUE THREAD

**Issue by JoshuaNovak919** [alanning/meteor-roles#85]
I am trying to get the count of how many users are in a particular role, but I can't seem to figure it out. I am new to Meteor, so it may be obvious and I just don't know what it is. Anyone have any ideas?

My code (doesn't work):
`Roles.getUsersInRole('admin').count()`

**Comment by d4nyll** [comment]
Your code works for me, what does it return?

**Comment by JoshuaNovak919** [comment]
Mine returns 0, but I have an admin user. I also have other users with different roles and it says zero for them too.

**Comment by d4nyll** [comment]
`Roles.getUsersInRole('admin').count()` is not the problem. It might be that the roles are not added to the users at all.

How are you adding the roles? When you `find` the `roles` collection (using `meteor mongo`, do you see the roles? When you `find` the `users` collections, do you see a property called `roles` with the documents?

Can you try adding the users in as described at the [Usage Examples](https://github.com/alanning/meteor-roles#usage-examples) and run `Roles.getUsersInRole('admin').count()` again and see if you get anything?

**Comment by alanning** [comment]
In addition to what Daniel asked, here's two other relevant questions:

* Are using groups?
* Are you running that on the client?

Particularly if you are running on the client, you will need to publish the roles field for each user that you want included in the count.

For reference, here is the source for the `getUsersInRole` function:

  https://github.com/alanning/meteor-roles/blob/master/roles/roles_common.js#L437-L484

**Comment by JoshuaNovak919** [comment]
It's odd, I can find the users by their role and it returns a LocalCollection.Cursor and in the collection map it shows the objects, but count returns 0. I do have the roles being published, but the users don't seem to have a role field when I do a `Meteor.users.findOne()`.

I'm adding users with this code:

```
if (Meteor.users.find().count() === 0) {
	var admins = [
      { name: "Some Admin", email: "someadmin@test.com", password: "password6", roles: ['admin'] }
    ];

  _.each(admins, function (user) {
    var id;

    id = Accounts.createUser({
      email: user.email,
      password: user.password,
      profile: { name: user.name }
    });

    if (user.roles.length > 0) {
      // Need _id of existing user record so this call must come 
      // after `Accounts.createUser` or `Accounts.onCreate`
      Roles.addUsersToRoles(id, user.roles);
    }

  });
}
```
