### ISSUE TITLE
how to manage branch office on roles?

### ISSUE THREAD

**Issue by yuomtheara** [alanning/meteor-roles#87]
I would to manage branch office on roles group like this:
```javascript
roles: {
   "Loan": {
      permission: ['insert', 'update' ...]
      branches: ['001', '002' ....]
   }
}
```
Please help me.

**Comment by alanning** [comment]
Not quite sure how to help here other than to suggest you fork the roles package and modify it to better fit your needs.

**Comment by yuomtheara** [comment]
thanks for your reply.
