### ISSUE TITLE
Error when adding roles

### ISSUE THREAD

**Issue by silentwarrior** [alanning/meteor-roles#91]
Hello.

I have this error, I was wondering if you could help me track it down :

Error : http://pastebin.com/fekPJU7J
My packages: http://pastebin.com/Z6bsERkp
My models: http://pastebin.com/LD9uN00m

**Comment by shkomg** [comment]
got the same error when upgraded to Meteor 1.0.4.1 & it still arises with Meteor 1.0.4.2, @alanning any suggestions? Thank you.

**Comment by alanning** [comment]
Hi @silentwarrior , @shkomg .  Thanks for the bug reports.  The roles package hasn't changed recently so I'd guess its a change to either Meteor or the underlying MongoDB version.

I'm having trouble reproducing this issue.  Can you publish a public repo to Github that reproduces this error, please?

**Comment by alanning** [comment]
If you guys can make a reproduction we can get to the bottom of this issue.

In the meantime, you could try moving `alanning:roles` to be just after `meteor-platform` in your `.meteor/packages` file.  We [found a case](https://github.com/alanning/meteor-roles/issues/94#issuecomment-85513947) where another package that modifies collections was causing issues and re-ordering is a confirmed work-around.  I'd be curious to hear if it has an effect in this case...

**Comment by shkomg** [comment]
Hi Adrian,

you see, my issue was related not to your package but to
```accounts-meld``` or even ```simpleSchema``` , pls, see the details here
https://github.com/splendido/meteor-accounts-meld/issues/11

Thank you for the prompt answer!

2015-03-24 16:56 GMT+02:00 Adrian Lanning <notifications@github.com>:

> If you guys can make a reproduction we can get to the bottom of this issue.
>
> In the meantime, you could try moving alanning:roles to be just after
> meteor-platform in your .meteor/packages file. We found a case
> <https://github.com/alanning/meteor-roles/issues/94#issuecomment-85513947>
> where another package that modifies collections was causing issues and
> re-ordering is a confirmed work-around. I'd be curious to hear if it has an
> effect in this case...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alanning/meteor-roles/issues/91#issuecomment-85540275>
> .
>



-- 
Best regards

Serhiy Khvashchuk
