### ISSUE TITLE
Error on meteor add alanning:roles

### ISSUE THREAD

**Issue by ianjonesidau** [alanning/meteor-roles#94]
I believe there's a bug in the roles init, which is preventing me from using the package, here's a summarised trace:

Error: use "new" to construct a Mongo.Collection
at new Mongo.Collection (packages/mongo/collection.js:29:1)
at [object Object].ns.Collection (packages/matb33:collection-hooks/collection-hooks.js:190:1)
at Roles (packages/alanning:roles/roles_server.js:9:1)
at packages/alanning:roles/roles_server.js:27:1

```javascript
Meteor.roles = new Meteor.Collection("roles")
```

Should be:

```javascript
Meteor.roles = new Mongo.Collection("roles")
```

I'm using Meteor 1.0.3.2

**Comment by alanning** [comment]
Thanks for the report.  Can you upload a reproduction to github, please?

I am having trouble reproducing this issue with Meteor 1.0.4.1 and 1.0.4.2.

**Comment by ianjonesidau** [comment]
What do you mean by reproduction? I can't share full project code unfortunately, although I'm willing to share pieces if that helps. Basically I got this error right after I installed the package and ran meteor again.

**Comment by alanning** [comment]
A reproduction in this case would be a minimal Meteor application that has the same issue.  Basically something I can `git clone ...` and see the issue happening.  Please see this section of the meteor wiki for more details:  https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor

The reason this is important is because the issue does not appear to happen with a clean app and adding the roles package.  So there is something that is happening in your actual app that is not in a simple app.  Often-times, just creating the reproduction helps identify where the problem lies (like noticing that it only happens once another package is added or something).

**Comment by ianjonesidau** [comment]
Thanks for the explanation, as you cant tell I'm a bit new to this process. I'll see what I can whip up to replicate the issue.

**Comment by ianjonesidau** [comment]
https://github.com/ianjonesidau/roles_bug_94

Ok, I reproduced it very easily:

* meteor create roles_bug_94
* meteor add sewdn:collection-behaviours
* meteor add alanning:roles
* meteor update --release 1.0.3.2

**Comment by alanning** [comment]
Thanks.  It seems that the problem starts when adding `sewdn:collection-behaviours`.  If I remove that package, it works.  So the next step is determining why that package causes the error...

**Comment by alanning** [comment]
Changing the load order of the packages fixes this:

.meteor/packages
```
meteor-platform
alanning:roles
sewdn:collection-behaviours
```

I guess collection-behaviours is doing something that causes the built-in aliasing of Meteor.Collection => Mongo.Collection to fail.

We can probably fix this in roles by using the newer syntax `Mongo.Collection` instead but haven't confirmed.

**Comment by ianjonesidau** [comment]
Yes this is what I was thinking, change the syntax as you mentioned. I'm looking into matb33:collection-hooks to see if I can figure out it's influence here.

**Comment by alanning** [comment]
Looks like `matb33:collection-hooks` doesn't cause the same issue so seems to be just `sewdn:collection-behaviours` (which uses collection-hooks).

**Comment by ianjonesidau** [comment]
sewdn:collection-behaviours refers to `Mongo.Collection.prototype = Object.create(constructor.prototype);` so I'd imagine this is relevant, although I'm having trouble fully understanding the source (lack of experience).

**Comment by alanning** [comment]
Yeah, for now I'd just make sure roles is first in your app's package list
file.

**Comment by ianjonesidau** [comment]
So you mean literally shift it before, within `.meteor/packages` ?

**Comment by ianjonesidau** [comment]
Huh, that actually worked... thanks so much!!!
