### ISSUE TITLE
IsInRole helper documentation wrong

### ISSUE THREAD

**Issue by jamgold** [alanning/meteor-roles#97]
there is a mistake in the documentation

```  {{#if isInRole 'admin' 'researchAndDevelopment'}} ```
should be
```  {{#if isInRole 'admin,researchAndDevelopment'}}```

**Comment by serenitus** [comment]
+1 Was just bitten by this too.

**Comment by alanning** [comment]
Thanks for pointing this out.  I think the snippet you are referencing is actually showing how to use groups with `isInRole`.  Not a very clear example though.  I'll rework it.

**Comment by jamgold** [comment]
Nice, thanks
