### ISSUE TITLE
Does meteor-roles support latest version meteor 1.0+?

### ISSUE THREAD

**Issue by tonyxiao** [alanning/meteor-roles#99]
README docs seem to imply that it doesn't. Are the docs out of date?

**Comment by jhuenges** [comment]
https://github.com/alanning/meteor-roles#meteor-09-new-packaging-system

I am using it with 1.0+ and have no problems

**Comment by alanning** [comment]
Thanks for the heads-up about this.  I'm sure it confused others as well.
